# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./MobileAppAPI
      run: dotnet restore ./MobileAppAPI.sln
    - name: Build
      working-directory: ./MobileAppAPI
      run: dotnet build --no-restore ./MobileAppAPI.sln
    - name: Test
      working-directory: ./MobileAppAPI
      run: dotnet test --no-build --verbosity normal ./MobileAppAPI.sln
